curl -X POST "https://upubmjqrydfnhtyziutl.supabase.co/auth/v1/token?grant_type=password" \
  -H "apikey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVwdWJtanFyeWRmbmh0eXppdXRsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODU5ODUzMzIsImV4cCI6MjEwMTU2MTMzMn0.Gm17BjUtFkyMxwPxmclndJFZvdFLomm3ymYBJxAFdR8" \
  -H "Content-Type: application/json" \
  -d '{"email":"minaeissa26@gmail.com","password":"123456"}'

###

curl -X 'POST' \
  'http://127.0.0.1:8000/api/v1/students/' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVwdWJtanFyeWRmbmh0eXppdXRsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODU5ODUzMzIsImV4cCI6MjEwMTU2MTMzMn0.Gm17BjUtFkyMxwPxmclndJFZvdFLomm3ymYBJxAFdR8'\
  -d '{
  "first_name": "kerolos",
  "middle_name": "fawzy",
  "last_name": "moheb",
  "school_id": "A1B2C3"
}'

###
curl -X 'GET' \
  'http://localhost:8000/api/v1/auth/me/'\
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -H 'Authorization: Bearer eyJhbGciOiJFUzI1NiIsImtpZCI6ImI2ZmIzYmMyLWQyNjEtNDRkZC05MmM5LTVmYzExY2I1ZGVlYiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL3VwdWJtanFyeWRmbmh0eXppdXRsLnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiIxNjA4MzE2ZS0wMDQzLTQ2MDctYmUyMi1mYjYzM2ViM2YyMjMiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzg2NDY0NTUxLCJpYXQiOjE3ODY0NjA5NTEsImVtYWlsIjoibWluYWVpc3NhMjZAZ21haWwuY29tIiwicGhvbmUiOiIiLCJhcHBfbWV0YWRhdGEiOnsicHJvdmlkZXIiOiJlbWFpbCIsInByb3ZpZGVycyI6WyJlbWFpbCJdfSwidXNlcl9tZXRhZGF0YSI6eyJlbWFpbF92ZXJpZmllZCI6dHJ1ZX0sInJvbGUiOiJhdXRoZW50aWNhdGVkIiwiYWFsIjoiYWFsMSIsImFtciI6W3sibWV0aG9kIjoicGFzc3dvcmQiLCJ0aW1lc3RhbXAiOjE3ODY0NjA5NTF9XSwic2Vzc2lvbl9pZCI6ImQxOWMyMzIwLTczNTktNGZjMy05MTViLTU4MWZlYTczMjJmZSIsImlzX2Fub255bW91cyI6ZmFsc2V9.MifQE3eA8CxV0-5APB72imAQu9GnNRKjVu_bfjCpIgfBc-gmeSqiTyThlgEi8tfCvSoYTZaRUt3D0BIYkMp1jw'


###

curl -X POST "https://upubmjqrydfnhtyziutl.supabase.co/auth/v1/token?grant_type=refresh_token" \
  -H "apikey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVwdWJtanFyeWRmbmh0eXppdXRsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODU5ODUzMzIsImV4cCI6MjEwMTU2MTMzMn0.Gm17BjUtFkyMxwPxmclndJFZvdFLomm3ymYBJxAFdR8" \
  -H "Content-Type: application/json" \
  -d '{"refresh_token":"dwmmm3rq66yb"}'