from django.urls import path, include
from rest_framework.routers import DefaultRouter

from .viewsets import (
    GradeViewSet,
    TeacherGradeViewSet,
    StudentViewSet,
    SessionViewSet,
    AttendanceViewSet,
    BathroomLogViewSet,
    BehaviorViewSet,
    SessionStudentBehaviorViewSet,
)
from .views import (
    BathroomStartView,
    BathroomStopView,
    SessionReportView,
    StudentBehaviorSummaryView,
    CreateUserView,
)

# --- standard CRUD, auto-generated by the router ---
router = DefaultRouter()
router.register("grades", GradeViewSet, basename="grade")
router.register("teacher-grades", TeacherGradeViewSet,
                basename="teacher-grade")
router.register("students", StudentViewSet, basename="student")
router.register("sessions", SessionViewSet, basename="session")
router.register("attendance", AttendanceViewSet, basename="attendance")
router.register("bathroom-logs", BathroomLogViewSet, basename="bathroom-log")
router.register("behaviors", BehaviorViewSet, basename="behavior")
router.register("behavior-events", SessionStudentBehaviorViewSet,
                basename="behavior-event")

urlpatterns = [
    path("", include(router.urls)),

    # --- business-logic endpoints, not covered by plain CRUD ---
    path("bathroom/start/", BathroomStartView.as_view(), name="bathroom-start"),
    path("bathroom/stop/", BathroomStopView.as_view(), name="bathroom-stop"),
    path("sessions/<uuid:session_id>/report/",
         SessionReportView.as_view(), name="session-report"),
    path(
        "students/<uuid:student_id>/behavior-summary/",
        StudentBehaviorSummaryView.as_view(),
        name="student-behavior-summary",
    ),
    path("users/create/", CreateUserView.as_view(), name="create-user"),
]
