from django.urls import path, include
from rest_framework.routers import DefaultRouter

from .viewsets import (
    AcademicYearViewSet,
    GradeViewSet,
    TeacherGradeViewSet,
    StudentViewSet,
    StudentGradeViewSet,
    SessionViewSet,
    AttendanceViewSet,
    BathroomLogViewSet,
    BehaviorViewSet,
    SessionStudentBehaviorViewSet,
    EventLogViewSet,
    SubjectViewSet,
)
from .views import (
    AttendanceForSessionView,
    BathroomStartView,
    BathroomStopView,
    BathroomLogsForStudentView,
    SessionReportView,
    StartSessionView,
    EndSessionView,
    StudentBehaviorSummaryView,
    GetAllOfUsersView,
    GetAllOfTeachersView,
    CreateUserView,
    SignInView,
    LogoutView,
    MeView,
)

# --- standard CRUD, auto-generated by the router ---
router = DefaultRouter()
router.register("academic-years", AcademicYearViewSet,
                basename="academic-year")
router.register("grades", GradeViewSet, basename="grade")
router.register("teacher-grades", TeacherGradeViewSet,
                basename="teacher-grade")
router.register("students", StudentViewSet, basename="student")
router.register("student-grades", StudentGradeViewSet,
                basename="student-grade")
router.register("sessions", SessionViewSet, basename="session")
router.register("subjects", SubjectViewSet, basename="subject")
router.register("attendance", AttendanceViewSet, basename="attendance")
router.register("bathroom-logs", BathroomLogViewSet, basename="bathroom-log")
router.register("behavior-tags", BehaviorViewSet, basename="behavior-tag")
router.register("behavior-events", SessionStudentBehaviorViewSet,
                basename="behavior-event")
router.register("event-logs", EventLogViewSet, basename="event-log")
urlpatterns = [

    # --- auth: signin / signup / me / logout ---
    path("auth/signin/", SignInView.as_view(), name="signin"),
    path("auth/me/", MeView.as_view(), name="me"),
    path("auth/logout/", LogoutView.as_view(), name="logout"),

    # --- business-logic endpoints, not covered by plain CRUD ---
    path("attendance/<uuid:session_id>/",
         AttendanceForSessionView.as_view(), name="attendance-for-session"),
    path("bathroom/start/", BathroomStartView.as_view(), name="bathroom-start"),
    path("bathroom/stop/", BathroomStopView.as_view(), name="bathroom-stop"),
    path("bathroom-logs/<uuid:student_id>/",
         BathroomLogsForStudentView.as_view(), name="bathroom-logs-for-student"),
    path("sessions/<uuid:session_id>/start/",
         StartSessionView.as_view(), name="session-start"),
    path("sessions/<uuid:session_id>/end/",
         EndSessionView.as_view(), name="session-end"),
    path("sessions/<uuid:session_id>/report/",
         SessionReportView.as_view(), name="session-report"),
    path(
        "students/<uuid:student_id>/behavior-summary/",
        StudentBehaviorSummaryView.as_view(),
        name="student-behavior-summary",
    ),
    path("users/create/", CreateUserView.as_view(), name="create-user"),
    path("users/", GetAllOfUsersView.as_view(), name="get-list-of-users"),
    path("teachers/", GetAllOfTeachersView.as_view(),
         name="get-list-of-teachers"),
    path("", include(router.urls)),
]
