# Generated by Django 6.1 on 2026-08-31 23:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('session_set', 'session_set'), ('session_started', 'session_started'), ('session_ended', 'session_ended'), ('grade_assigned', 'grade_assigned')], max_length=20)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'event_log',
                'ordering': ['-occurred_at'],
                'managed': False,
            },
        ),
    ]
